# Generated by Django 2.2.1 on 2019-08-12 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('userid', models.UUIDField(default='00634', editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(default='something-107@gmail.com', max_length=100)),
                ('age', models.IntegerField(default=34)),
            ],
        ),
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('skill', models.CharField(choices=[('Beginner', 'Beginner'), ('Moderate', 'Moderate'), ('Expert', 'Expert')], max_length=100)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammingLanguages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('skill', models.CharField(choices=[('Beginner', 'Beginner'), ('Moderate', 'Moderate'), ('Expert', 'Expert')], max_length=100)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.UserInfo')),
            ],
        ),
    ]
