# Generated by Django 2.2.1 on 2019-08-14 21:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contacts',
            name='age',
            field=models.IntegerField(default=23),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.CharField(default='something-749@gmail.com', max_length=100),
        ),
    ]
