# Generated by Django 2.2.1 on 2019-08-14 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20190814_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='age',
            field=models.IntegerField(default=37),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.CharField(default='something-839@gmail.com', max_length=100),
        ),
    ]
